/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#4b8eff",
        "surface": "#111415",
        "on-secondary-fixed": "#00105c",
        "surface-bright": "#373a3b",
        "on-primary": "#002e69",
        "tertiary-container": "#00a741",
        "on-primary-container": "#00285c",
        "on-tertiary": "#003911",
        "on-background": "#e1e3e4",
        "primary-fixed": "#d8e2ff",
        "inverse-surface": "#e1e3e4",
        "tertiary": "#53e16f",
        "primary": "#adc6ff",
        "on-secondary-container": "#a8b4ff",
        "tertiary-fixed": "#72fe88",
        "secondary-fixed": "#dee0ff",
        "surface-container": "#1d2021",
        "surface-container-low": "#191c1d",
        "surface-container-highest": "#323536",
        "on-error-container": "#ffdad6",
        "outline": "#8b90a0",
        "on-tertiary-fixed": "#002107",
        "secondary": "#bac3ff",
        "on-secondary": "#08218a",
        "on-tertiary-container": "#00320e",
        "primary-fixed-dim": "#adc6ff",
        "on-surface-variant": "#c1c6d7",
        "surface-tint": "#adc6ff",
        "background": "#111415",
        "surface-variant": "#323536",
        "on-surface": "#e1e3e4",
        "outline-variant": "#414755",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "inverse-on-surface": "#2e3132",
        "on-tertiary-fixed-variant": "#00531c",
        "on-primary-fixed-variant": "#004493",
        "on-secondary-fixed-variant": "#293ca0",
        "inverse-primary": "#005bc1",
        "error-container": "#93000a",
        "on-primary-fixed": "#001a41",
        "secondary-container": "#2c3ea3",
        "surface-dim": "#111415",
        "secondary-fixed-dim": "#bac3ff",
        "tertiary-fixed-dim": "#53e16f",
        "surface-container-high": "#282a2b",
        "surface-container-lowest": "#0c0f10"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "manrope": ["Manrope", "sans-serif"],
        "inter": ["Inter", "sans-serif"]
      },
    },
  },
  plugins: [],
}
